name: Link Check

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '14 6 * * *'  # Runs every day at 06:14 UTC

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install linkchecker
        run: pip install linkchecker
      - name: Run linkchecker script
        run: python check_links.py
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: linkchecker-results
          path: linkchecker_results/